baseURL = "/"
enableRobotsTXT = true
languageCode = "en-us"
theme = "custobar"
title = "Custobar"
[params]
metaDescription = "Custobar"
shareDescription = "Custobar"
shareImage = "/uploads/2017/11/26/share.jpg"
shareTitle = "Custobar"
[params.header.logo]
src = "images-theme/custobar_logo.png"
alt = "Custobar"
url = "/"
[params.header.button]
title = "Book a demo"
url = "/book-a-demo/"
[[params.topNavigation]]
title = 'Features'
url = '/#features'
[[params.topNavigation]]
title = 'Pricing'
url = '/#pricing'
[[params.topNavigation]]
title = 'Support'
url = '/#supprot'
[[params.topNavigation]]
title = 'Partners'
url = '/partners/'
[[params.topNavigation]]
title = 'Blog'
url = '/blog/'
[params.copyright]
text = 'Copyright Â© 2018 Custobar '
[params.privacy_link]
text = "Privacy Policy"
url = "/"
[[params.socialNetwork]]
icon = "/images-theme/linkedin.png"
title = "linkedin"
link = "/"
[[params.socialNetwork]]
icon = "/images-theme/facebook.png"
title = "Facebook"
link = "/"
[[params.socialNetwork]]
icon = "/images-theme/twitter.png"
title = "Twitter"
link = "/"
